import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from 'next/link';
import "./globals.css";
import 'tailwindcss/tailwind.css'
// import 'bootstrap/dist/css/bootstrap.min.css';
import AppHeader from "./components/app.header";
import AppFooter from "./components/app.footer";
import Nav from 'react-bootstrap/Nav';
import Navbar from 'react-bootstrap/Navbar';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
    }: Readonly<{
    children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} style={{
            margin: "0px 0px 0px 0px"
      }}>
      <AppHeader/>
      <div className="container">
      <div className="sidebar">
        <div className ="navbar">
          <div>
            <Link href="/">Thông tin y tá</Link>
          </div>
          <div>
            <Link href="/chat">Chat</Link>
          </div>
          <div>
            <Link href="/hearthRecord">Kiểm tra hồ sơ</Link>
          </div>
        </div>
      </div>
      <div className="content">

        {children}
      </div>
      
    </div>
    <AppFooter />
      </body>
    </html>
  );
}
